# leave a command empty to disable it. Anything but system update will also become hidden.
# Use the following to run a systemd service: ./service-as-program.sh your-system.service
[Commands]
systemUpdateCommand=./service-as-program.sh uupd-manual.service
systemRollbackCommand=bazzite-rollback-helper rollback -y

# modify the KAboutData object for the OS in ./KAboutData_OS.json
