[General]
# Supported values: atom, rss2, rss1
rssFeedType=rss1
rssFeed=https://www.debian.org/News/news

# leave a command empty to disable it. Anything but system update will also become hidden.
# Use the following to run a systemd service: ./service-as-program.sh your-system.service
[Commands]
# When true, allow commands to be stopped mid-run by closing the app. Set to false if your configured commands do not gracefully handle being killed unexpectedly.
allowEarlyExit=false
systemUpdateCommand=pkexec apt-get update && pkexec DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -q 
systemRollbackCommand=exit 1 # Debian Linux does not have an update rollback command preconfigured. You can configure one and apply it within the file /etc/bazzite-updater/config.ini to access it!

# modify the KAboutData object for the OS in ./KAboutData_OS.json
